Message.create!(content: 'My first text!')
Message.create!(content: 'My second text!')
Message.create!(content: 'My third text!')
Message.create!(content: 'My fourth text!')
Message.create!(content: 'My fifth text!')
